version: '3.8'

services:
  app:
    image: ringle-app-v1
    container_name: ringle-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PW=${MYSQL_PW}
    networks:
      - ringle-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/sites-available/default:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - ringle-network

networks:
  ringle-network:
    driver: bridge