spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

swagger:
  tag:
    test: 'A. Test API'

spring-doc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
